################################################################################
#	\file   SConstruct
#	\author Gregory Diamos <gregory.diamos@gatech.edu>
#   \date   Tuesday February 21, 2012
#	\brief  The SCons master build script for vanaheimr
################################################################################

if ARGUMENTS.get('mode', 'release') == 'debug':
	SConscript('SConscript', variant_dir='.debug_build',   duplicate=0, 
		exports={'mode':'debug'})
else:
	SConscript('SConscript', variant_dir='.release_build', duplicate=0,
		exports={'mode':'release'})

